# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Region list https://fly.io/docs/reference/regions/#fly-io-regions
primary_region = "hkg"
app = "sxq"

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
destination = "/opt/alist/data"
source = "data"
