name: Fly Deploy
on:
  workflow_dispatch:
    branches:
      - v3
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth token
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
